python src/main.py --output_dir output \
                   --comment "fintune for regression" \
                   --name BeijingPM25Quality_finetunes \
                   --records_file Regression_records.xls \
                   --data_dir ./data/BeijingPM25Quality/ \
                   --data_class tsra \
                   --pattern TRAIN \
                   --val_ratio 0.2 \
                   --epochs 200 \
                   --lr 0.001 \
                   --batch_size 128 \
                   --optimizer RAdam \
                   --load_model  \
                   --pos_encoding learnable \
                   --task regression \
                   --shuffle False \
                   --d_model 128 \
                   --model transformer \